### ISSUE TITLE
dependencies when running tutorials

### ISSUE THREAD

**Issue by mbensouda** [SchubertLab/mvTCR#7]
Hi, I followed the instructions for the installation of mvTCR (using the documentation) but I run into this error when importing scanpy:

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/mbensouda/miniconda3/envs/mvTCR/lib/python3.8/site-packages/scanpy/__init__.py", line 13, in <module>
    from . import plotting as pl
  File "/share/mbensouda/miniconda3/envs/mvTCR/lib/python3.8/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import scatter, violin, ranking, clustermap, tracksplot, dendrogram, correlation_matrix, heatmap
  File "/share/mbensouda/miniconda3/envs/mvTCR/lib/python3.8/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
    from . import _utils
  File "/share/mbensouda/miniconda3/envs/mvTCR/lib/python3.8/site-packages/scanpy/plotting/_utils.py", line 36, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
`
Thank you for your help!

**Comment by leuschjanphilipp** [comment]
Hi,
try to change the version of matplotlib to <3.7 (e.g. 3.6.3) as it causes this problem (https://discourse.scverse.org/t/metaclass-conflict-from-trying-to-import-scanpy/1133).

Best,
Jan

**Comment by ArcaneEmergence** [comment]
Thank you Jan!

**Comment by mbensouda** [comment]
Thank you so much for this fast reply!
